export const TEXTURE_DOWNSAMPLE = 1,
  DENSITY_DISSIPATION = 0.97,
  VELOCITY_DISSIPATION = 0.98,
  PRESSURE_DISSIPATION = 0.8,
  PRESSURE_ITERATIONS = 25,
  SPLAT_RADIUS = 0.0012,
  VORTICITY_AMOUNT = 12;
